const projectsData = [
    {
        name: "Saathi",
        productDev: 1,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 1,
        uxResearch: 1,
        prototyping: 1,
        techForGood: 1,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Dr. Anveshna Srivastava",
        course: "NaN",
        finance: 0,
        link: "https://play.google.com/store/apps/details?id=com.acm.saathi"
    },
    {
        name: "Studata",
        productDev: 1,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 1,
        uiDesign: 1,
        uxResearch: 1,
        prototyping: 1,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Human AI Interaction",
        finance: 0,
        link: "https://studata-vxsr.onrender.com/"
    },
    {
        name: "Superwiser",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 1,
        uxResearch: 1,
        prototyping: 1,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Human Computer Interaction",
        finance: 0,
        link: "https://drive.google.com/drive/folders/1E5UxkKVJCFd5aFRidNctPnNFPpW8ksMq?usp=drive_link"
    },
    {
        name: "Carbon Data Analysis",
        productDev: 1,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 1,
        uiDesign: 1,
        uxResearch: 0,
        prototyping: 1,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Dr. Sruti S Ragavan",
        course: "Undergraduate Project",
        finance: 0,
        link: "https://www.canva.com/design/DAG4Ys3yd0k/vssNbKtH0xi1Ju85JCttNQ"
    },
    {
        name: "Deutsche Bank Internship",
        productDev: 1,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 1,
        uiDesign: 1,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Prachi Gala",
        course: "Deutsche Bank Internship",
        finance: 1,
        link: "NaN"
    },
    {
        name: "Flankers Replication Study",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 1,
        dataScience: 1,
        uiDesign: 0,
        uxResearch: 1,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Introduction to Cognitive Science",
        finance: 0,
        link: "https://drive.google.com/file/d/1Jog6GijayrbxRbqAvD9CXDdWWFTEExy6/view?usp=drive_link"
    },
    {
        name: "Companion Arbiter PUF",
        productDev: 0,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Introduction to Machine Learning",
        finance: 0,
        link: "https://drive.google.com/drive/folders/16jmcTcC4lV8SSiDKmVMaCKkVEuH0nYk-?usp=drive_link"
    },
    {
        name: "REDev",
        productDev: 1,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 1,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Competition",
        course: "NaN",
        finance: 0,
        link: "restox.onrender.com"
    },
    {
        name: "Convolve 2.0",
        productDev: 0,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Competition",
        course: "NaN",
        finance: 0,
        link: "NaN"
    },
    {
        name: "Bank of Baroda Hackathon",
        productDev: 1,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 1,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Competition",
        course: "NaN",
        finance: 1,
        link: "https://drive.google.com/file/d/1KUE7s4505CiDOLPvi3tMOwTTOPpX_pe9/view?usp=drive_link"
    },
    {
        name: "A Literature Survey on Environmental Factors Influencing Productivity",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 1,
        dataScience: 1,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 1,
        graphicDesign: 0,
        groupProject: 0,
        mentor: "Dr. Anubha Goel",
        course: "Undergraduate Project",
        finance: 0,
        link: "https://drive.google.com/file/d/1534GkrdeFG3hDTTaCn7iqSrURdCPDqY7/view?usp=drive_link"
    },
    {
        name: "Analysis of Load-Limiting Devices in Suspension Towers",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 1,
        dataScience: 0,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 0,
        mentor: "Dr. Chinmoy Kolay",
        course: "SURGE IITK",
        finance: 0,
        link: "https://drive.google.com/file/d/1ijOVrqBu5R9Ou0HaX42TCGP4vGFAgt2h/view?usp=drive_link"
    },
    {
        name: "Real-time Captioning System with CDAP",
        productDev: 1,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 1,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 1,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Self Project",
        course: "NaN",
        finance: 0,
        link: "NaN"
    },
    {
        name: "You are what you Remember",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 1,
        graphicDesign: 1,
        groupProject: 0,
        mentor: "Course Project",
        course: "Applied Cognitive Science",
        finance: 0,
        link: "https://www.canva.com/design/DAGfKheR62A/vSOmLU3ZSZfY23bn0JOzJw/"
    },
    {
        name: "Pingala Redesign",
        productDev: 0,
        aiMl: 1,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 1,
        uxResearch: 1,
        prototyping: 1,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Human AI Interaction",
        finance: 0,
        link: "https://drive.google.com/file/d/1xcetMbFQIfCp2VDBuK0E7ivA8rfmIt3B/view?usp=drive_link"
    },
    {
        name: "Spotify Review Analysis",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 0,
        uxResearch: 1,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Human Computer Interaction",
        finance: 0,
        link: "NaN"
    },
    {
        name: "Investment Banking Virtual Experience",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 0,
        mentor: "Self Project",
        course: "JP Morgan Chase via Forage",
        finance: 1,
        link: "NaN"
    },
    {
        name: "Biodiversity Assessment of IITK",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 1,
        dataScience: 1,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 1,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Ecological and Biological Principles and Processes",
        finance: 0,
        link: "https://www.canva.com/design/DAG4N2LTK34/IUfQlr-utWrPEQU_VWXIww"
    },
    {
        name: "Iris: Lock your Money",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 1,
        groupProject: 0,
        mentor: "Competition",
        course: "DesignUp Futures Challenge",
        finance: 0,
        link: "https://drive.google.com/file/d/1WSNKPnbn512YBLQ-PKrpwwdsuFGWWwJy/view?usp=drive_link"
    },
    {
        name: "Dunning Kruger and Personality Influences in Action",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 1,
        dataScience: 1,
        uiDesign: 0,
        uxResearch: 1,
        prototyping: 0,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 0,
        mentor: "Course Project",
        course: "Introduction to Cognitive Science",
        finance: 0,
        link: "https://drive.google.com/file/d/1IqT5_ojtfDJJMX2GqOAitGuF2JRjm4OL/view?usp=drive_link"
    },
    {
        name: "Water Resource Management in the Mississipi Basin",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 1,
        dataScience: 1,
        uiDesign: 0,
        uxResearch: 0,
        prototyping: 0,
        techForGood: 1,
        graphicDesign: 0,
        groupProject: 1,
        mentor: "Course Project",
        course: "Water Resource Systems Analysis",
        finance: 0,
        link: "https://drive.google.com/drive/folders/1MirQViCopLiInX0Lzn8cQ7XkOGmBLyFt?usp=drive_link"
    },
    {
        name: "DOAA Website Redesign",
        productDev: 0,
        aiMl: 0,
        engineeringTech: 0,
        dataScience: 0,
        uiDesign: 1,
        uxResearch: 0,
        prototyping: 1,
        techForGood: 0,
        graphicDesign: 0,
        groupProject: 0,
        mentor: "Course Project",
        course: "Human Computer Interaction",
        finance: 0,
        link: "https://drive.google.com/file/d/1waqUhSq0KSsib4hNn6yX-zQGeg2_p4oC/view?usp=drive_link"
    }
];
